#ddev-generated
# Installs Hugo (extended edition) from the official gohugoio/hugo releases.
#
# To use a different Hugo release, change HUGO_VERSION below and run
# `ddev restart`. Removing the `#ddev-generated` line on top of this file
# marks it as user-modified, so `ddev add-on get` will no longer overwrite it.
ARG HUGO_VERSION="0.166.0"

RUN set -eu; \
    arch="$(dpkg --print-architecture)"; \
    deb="hugo_extended_${HUGO_VERSION}_linux-${arch}.deb"; \
    curl -fsSL -o "/tmp/${deb}" "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${deb}"; \
    dpkg -i "/tmp/${deb}"; \
    rm -f "/tmp/${deb}"; \
    hugo version
